### ISSUE TITLE
Версия под arm

### ISSUE THREAD

**Issue by MaksimovAL** [ebuyan/yapi#1]
Добрый день, пользуюсь Yapi уже давно, большое спасибо за вашу работу! 

Сам я в Go не силён, пытаюсь собрать под arm последний коммит и получаю «import cycle not allowed». Если вам не трудно, могли бы вы, пожалуйста, собрать последний версию yapi под arm? 

И я так понимаю, что в последнем коммите не нужны больше логин/пароль от Я-аккаунта, а достаточно токена, верно?

С Уважением!

**Comment by ebuyan** [comment]
Привет, не знал что кто-то пользуется) Я запушил сборку под арм, проблем не возникло, может не на последнем коммите все же собирали?
На счет токена. Тот вариант авторизации по логину и паролю в яндексе, который у меня был реализован, перестал работать, видимо у яндекса, что-то поменялось. Пока что оставил только по токену работу. Насколько помню, достать его нет проблем

**Comment by MaksimovAL** [comment]
Спасибо большое за yapi_arm! :) У меня на одноплатнике стоит, до этого работал стабильно. Собирал на последнем коммите, но скорей всего просто делал это не корректно, не успел ещё разобраться)

Яндекс, да, прибил старый способ, вот [тут](https://github.com/MarshalX/yandex-music-api/discussions/513) описаны актуальные способы получения токена.

Спасибо ещё раз больше за вашу работу!

UPD: Всё работает! :)

**Comment by MaksimovAL** [comment]
Привет! Yapi перестал связываться со станцией (токен и ID станции верный), пишет: no station found in local network. Вопрос, это только у меня какой-то косяк или Яндекс прикрыл возможность?

**Comment by ebuyan** [comment]
Привет, а глянь предпоследний коммит, там апи глагола обратную совместимость сломала. Я пересобрал тебе под арм

**Comment by MaksimovAL** [comment]
Спасибо, проверил, не помогло. По всей видимости, что-то с самой станцией, буду разбираться.
